/** Rules already off the masters when masters.test.ts came in (2026-10-08). Shrink only: delete a line when its rule moves onto a master. */
export const KNOWN: string[] = [
  "components/BuildUp.tsx | <button class=\"lesson\">",
  "components/Contents.tsx | <button class=\"on\">",
  "components/Contents.tsx | <button class=\"tlink\">",
  "components/Contents.tsx | <button class=\"zcard\">",
  "components/Island.tsx | <button class=\"iback\">",
  "components/Island.tsx | <button class=\"icon\">",
  "components/Island.tsx | <button class=\"imine\">",
  "components/Island.tsx | <button class=\"iplace\">",
  "components/Island.tsx | <button class=\"iresume\">",
  "components/Island.tsx | <button class=\"iresume-x\">",
  "components/Nav.tsx | <button class=\"imark\">",
  "components/PageTile.tsx | <button class=\"mtoggle\">",
  "components/Shelf.tsx | <button class=\"cls\">",
  "components/practice/Keypad.tsx | <button class=\"k-\">",
  "components/primitives/MathLine.tsx | <button class=\"cls\">",
  "screens/Facts.tsx | <button class=\"fcell\">",
  "screens/Facts.tsx | <button class=\"fchip\">",
  "screens/GradeQuestion.tsx | <button class=\"tlink\">",
  "screens/Home.tsx | <button class=\"lesson\">",
  "screens/Home.tsx | <button class=\"pitem\">",
  "screens/Home.tsx | <button class=\"tlink\">",
  "screens/Learn.tsx | <button class=\"icon\">",
  "screens/Learn.tsx | <button class=\"tlink\">",
  "screens/Practice.tsx | <button class=\"choice\">",
  "screens/Practice.tsx | <button class=\"speak\">",
  "screens/Settings.tsx | <button class=\"st\">",
  "screens/Welcome.tsx | <button class=\"tlink\">",
  "styles/base.css | .wrap | gap",
  "styles/components.css | .actions | gap",
  "styles/components.css | .ask | gap",
  "styles/components.css | .b-stats .gtline | gap",
  "styles/components.css | .b-weak .lessons | gap",
  "styles/components.css | .bar | background",
  "styles/components.css | .bar | gap",
  "styles/components.css | .bb .cube | background",
  "styles/components.css | .bb .cube | border-radius",
  "styles/components.css | .bb .rod | background",
  "styles/components.css | .bb .rod | border-radius",
  "styles/components.css | .bb | gap",
  "styles/components.css | .bcol | gap",
  "styles/components.css | .bento | background",
  "styles/components.css | .bento>div | gap",
  "styles/components.css | .bgrown | column-gap",
  "styles/components.css | .bgrown | gap",
  "styles/components.css | .bhome .b-stats | background",
  "styles/components.css | .bhome .b-stats | column-gap",
  "styles/components.css | .bhome .b-stats | gap",
  "styles/components.css | .bhome .b-weak | background",
  "styles/components.css | .bhome .today | background",
  "styles/components.css | .bhome | gap",
  "styles/components.css | .blearn | gap",
  "styles/components.css | .bme | gap",
  "styles/components.css | .card .badge | background",
  "styles/components.css | .card .badge.on | background",
  "styles/components.css | .card .ctl | background",
  "styles/components.css | .card .ctl.go | background",
  "styles/components.css | .card .ctl:active | background",
  "styles/components.css | .card .ctl:hover | background",
  "styles/components.css | .card | background",
  "styles/components.css | .card | gap",
  "styles/components.css | .chip i | background",
  "styles/components.css | .chip | background",
  "styles/components.css | .chip | gap",
  "styles/components.css | .confetti i | background",
  "styles/components.css | .confetti i | border-radius",
  "styles/components.css | .ctl .badge | background",
  "styles/components.css | .ctl .badge.on | background",
  "styles/components.css | .ctl.go .badge | background",
  "styles/components.css | .donehead | gap",
  "styles/components.css | .donetext | gap",
  "styles/components.css | .dot | background",
  "styles/components.css | .dotrow | gap",
  "styles/components.css | .dots-nav | gap",
  "styles/components.css | .facts .pattern>span:first-child | gap",
  "styles/components.css | .facts | background",
  "styles/components.css | .facts>div | gap",
  "styles/components.css | .fb-bad | background",
  "styles/components.css | .fb-good | background",
  "styles/components.css | .fb-hint | background",
  "styles/components.css | .feedback | gap",
  "styles/components.css | .gbadge b | background",
  "styles/components.css | .gcell | background",
  "styles/components.css | .gcell | gap",
  "styles/components.css | .head | gap",
  "styles/components.css | .helptile | gap",
  "styles/components.css | .hero | background",
  "styles/components.css | .hero | gap",
  "styles/components.css | .learn .card | gap",
  "styles/components.css | .lesson | background",
  "styles/components.css | .lesson | gap",
  "styles/components.css | .lesson.resume | background",
  "styles/components.css | .lesson:active | background",
  "styles/components.css | .lesson:hover | background",
  "styles/components.css | .lessons | gap",
  "styles/components.css | .line | gap",
  "styles/components.css | .lineup | gap",
  "styles/components.css | .lside | gap",
  "styles/components.css | .lspeak | gap",
  "styles/components.css | .math | gap",
  "styles/components.css | .mhero | background",
  "styles/components.css | .mhero | gap",
  "styles/components.css | .mixed | gap",
  "styles/components.css | .mlist>div>span | gap",
  "styles/components.css | .mseg | background",
  "styles/components.css | .mseg | gap",
  "styles/components.css | .mstats | gap",
  "styles/components.css | .mstats>div | background",
  "styles/components.css | .mstats>div | gap",
  "styles/components.css | .mtile .actions | gap",
  "styles/components.css | .mtile .ctl | background",
  "styles/components.css | .mtile .ctl.go | background",
  "styles/components.css | .mtoggle[aria-checked=\"true\"] .switch | background",
  "styles/components.css | .outline .on .badge | background",
  "styles/components.css | .outline .seen .badge | background",
  "styles/components.css | .outline button | gap",
  "styles/components.css | .outline button.on | background",
  "styles/components.css | .outline button:not([disabled]):active | background",
  "styles/components.css | .outline button:not([disabled]):hover | background",
  "styles/components.css | .outline | background",
  "styles/components.css | .outline | gap",
  "styles/components.css | .panel .ctl | background",
  "styles/components.css | .panel .ctl.go | background",
  "styles/components.css | .panel .ctl:active | background",
  "styles/components.css | .panel .ctl:hover | background",
  "styles/components.css | .pdots | gap",
  "styles/components.css | .phead | gap",
  "styles/components.css | .pitem | gap",
  "styles/components.css | .pitem.done .pmark | background",
  "styles/components.css | .pitem:active | background",
  "styles/components.css | .pitem:hover | background",
  "styles/components.css | .placed | gap",
  "styles/components.css | .plan | gap",
  "styles/components.css | .probs details.card | border-radius",
  "styles/components.css | .probs summary | gap",
  "styles/components.css | .probs | gap",
  "styles/components.css | .prose | gap",
  "styles/components.css | .ptext | gap",
  "styles/components.css | .score b | background",
  "styles/components.css | .score | gap",
  "styles/components.css | .seg button.on | background",
  "styles/components.css | .seg | background",
  "styles/components.css | .seg | gap",
  "styles/components.css | .sheet | background",
  "styles/components.css | .slegend li | gap",
  "styles/components.css | .slegend | gap",
  "styles/components.css | .slot | background",
  "styles/components.css | .slot | border-radius",
  "styles/components.css | .slot.active | background",
  "styles/components.css | .slot.empty | background",
  "styles/components.css | .speak:active | background",
  "styles/components.css | .speak:hover | background",
  "styles/components.css | .stats .v | gap",
  "styles/components.css | .stats | background",
  "styles/components.css | .stats>div | gap",
  "styles/components.css | .steps | gap",
  "styles/components.css | .strip span.g | background",
  "styles/components.css | .strip | border-radius",
  "styles/components.css | .strips | gap",
  "styles/components.css | .switch i | background",
  "styles/components.css | .switch | background",
  "styles/components.css | .tf i | background",
  "styles/components.css | .tf i.on::after | background",
  "styles/components.css | .tf | background",
  "styles/components.css | .tf | border-radius",
  "styles/components.css | .tf | gap",
  "styles/components.css | .unit | gap",
  "styles/components.css | .units .lesson | gap",
  "styles/components.css | .units .lesson:not([disabled]):active | background",
  "styles/components.css | .units .lesson:not([disabled]):hover | background",
  "styles/components.css | .units .lessons | gap",
  "styles/components.css | .units | gap",
  "styles/components.css | .units>.panel | background",
  "styles/components.css | .units>.panel | gap",
  "styles/components.css | .upnext .row | gap",
  "styles/components.css | .upnext | background",
  "styles/components.css | .upnext | gap",
  "styles/components.css | .work | background",
  "styles/components.css | .workline | gap",
  "styles/components.css | .wrap .mtile .ctl:not(.go) | background",
  "styles/components.css | .wrap .mtile | background",
  "styles/components.css | .wrap .mtoggle:hover | background",
  "styles/components.css | .wrap .mtoggle:not([aria-checked=\"true\"]) .switch | background",
  "styles/components.css | .wrap .seg button.on | background",
  "styles/components.css | .wrap .seg | background",
  "styles/components.css | .wrap :is(.mtoggle,.mseg) | background",
  "styles/facts.css | .fans | background",
  "styles/facts.css | .fans.miss | background",
  "styles/facts.css | .fbar | background",
  "styles/facts.css | .fcell | background",
  "styles/facts.css | .fcell | border-radius",
  "styles/facts.css | .fcell.on | background",
  "styles/facts.css | .fcell.twin | background",
  "styles/facts.css | .fchip | background",
  "styles/facts.css | .fchip | border-radius",
  "styles/facts.css | .fchip | gap",
  "styles/facts.css | .fchip.miss | background",
  "styles/facts.css | .fchip.on | background",
  "styles/facts.css | .fdone | gap",
  "styles/facts.css | .fgrid | gap",
  "styles/facts.css | .fgridwrap | gap",
  "styles/facts.css | .fhundred .seg button[aria-pressed=true] | background",
  "styles/facts.css | .fhundred | gap",
  "styles/facts.css | .fq | gap",
  "styles/facts.css | .frowlist | gap",
  "styles/facts.css | .ftable | gap",
  "styles/facts.css | .ftable.panel | background",
  "styles/facts.css | .ftables | gap",
  "styles/facts.css | .h100 span | background",
  "styles/facts.css | .h100 span | border-radius",
  "styles/facts.css | .h100 span.on | background",
  "styles/facts.css | .h100 | gap",
  "styles/facts.css | .tlinks | column-gap",
  "styles/grade-picker.css | .b2d .ctl[aria-pressed=\"true\"] | background",
  "styles/grade-picker.css | .b2pic | background",
  "styles/grade-picker.css | .gdgo | gap",
  "styles/grade-picker.css | .gdgo.gpal .ctl.go | background",
  "styles/grade-picker.css | .gdl .gdtext | gap",
  "styles/grade-picker.css | .gdl | background",
  "styles/grade-picker.css | .gdl | gap",
  "styles/grade-picker.css | .gdpic | background",
  "styles/grade-picker.css | .gdpic | gap",
  "styles/grade-picker.css | .gqline | gap",
  "styles/grade-picker.css | .slist .gqh | gap",
  "styles/grade-picker.css | .srow.grow | gap",
  "styles/grade-picker.css | .trow .ticon | background",
  "styles/grade-picker.css | .trow .ticon | border-radius",
  "styles/grade-picker.css | .trow | gap",
  "styles/grade-picker.css | :root[data-side=\"b2\"] body | background",
  "styles/grownup.css | .gu .gu-bars | gap",
  "styles/grownup.css | .gu .gu-card | background",
  "styles/grownup.css | .gu .gu-card | gap",
  "styles/grownup.css | .gu .gu-col | background",
  "styles/grownup.css | .gu .gu-col | gap",
  "styles/grownup.css | .gu .gu-col>.k | gap",
  "styles/grownup.css | .gu .gu-ex | gap",
  "styles/grownup.css | .gu .gu-ex.nopic | gap",
  "styles/grownup.css | .gu .gu-foot | gap",
  "styles/grownup.css | .gu .gu-hb .tr i | border-radius",
  "styles/grownup.css | .gu .gu-hb .tr | background",
  "styles/grownup.css | .gu .gu-hb .tr | border-radius",
  "styles/grownup.css | .gu .gu-hb | gap",
  "styles/grownup.css | .gu .gu-home | background",
  "styles/grownup.css | .gu .gu-legend | gap",
  "styles/grownup.css | .gu .gu-mcard | gap",
  "styles/grownup.css | .gu .gu-mh | gap",
  "styles/grownup.css | .gu .gu-more .ctl | background",
  "styles/grownup.css | .gu .gu-rate .badge | background",
  "styles/grownup.css | .gu .gu-rate | background",
  "styles/grownup.css | .gu .gu-rate | gap",
  "styles/grownup.css | .gu .gu-row | gap",
  "styles/grownup.css | .gu .gu-s .n | background",
  "styles/grownup.css | .gu .gu-s | background",
  "styles/grownup.css | .gu .gu-s | gap",
  "styles/grownup.css | .gu .gu-s.bad | background",
  "styles/grownup.css | .gu .gu-s.good | background",
  "styles/grownup.css | .gu .gu-s.shown | background",
  "styles/grownup.css | .gu .gu-say | background",
  "styles/grownup.css | .gu .gu-stat .ic | background",
  "styles/grownup.css | .gu .gu-stat | background",
  "styles/grownup.css | .gu .gu-stat | gap",
  "styles/grownup.css | .gu .gu-stats | gap",
  "styles/grownup.css | .gu .ibat | background",
  "styles/grownup.css | .gu .ibat.p4>i | background",
  "styles/grownup.css | .gu .ibat>i | background",
  "styles/grownup.css | .gu .slbl | gap",
  "styles/grownup.css | .gu .slist .gu-stat>div | gap",
  "styles/grownup.css | .gu .slist .gu-stats | gap",
  "styles/grownup.css | .gu .slist .shead | gap",
  "styles/grownup.css | .island .ilock | background",
  "styles/grownup.css | .island .ilock | gap",
  "styles/landing.css | .adv-course | background",
  "styles/landing.css | .adv-course | gap",
  "styles/landing.css | .adv-courses | gap",
  "styles/landing.css | .adv-foot | gap",
  "styles/landing.css | .adv-ghost | gap",
  "styles/landing.css | .adv-tease | gap",
  "styles/landing.css | .adv-tools | gap",
  "styles/landing.css | .ladv | background",
  "styles/landing.css | .ladv | gap",
  "styles/landing.css | .land | gap",
  "styles/landing.css | .lbatt | gap",
  "styles/landing.css | .lbook span | background",
  "styles/landing.css | .lbook span | border-radius",
  "styles/landing.css | .lbook | border-radius",
  "styles/landing.css | .lbook | gap",
  "styles/landing.css | .lbook.z0 .page | border-radius",
  "styles/landing.css | .lbook.z2 span:not(.page) | background",
  "styles/landing.css | .lbook.z2 | background",
  "styles/landing.css | .lbox | gap",
  "styles/landing.css | .lchip | background",
  "styles/landing.css | .lcount | gap",
  "styles/landing.css | .lcta | gap",
  "styles/landing.css | .lfacts span | background",
  "styles/landing.css | .lfacts span | border-radius",
  "styles/landing.css | .lfacts | gap",
  "styles/landing.css | .lhbox | gap",
  "styles/landing.css | .lhelp span | background",
  "styles/landing.css | .lhelp span.on | background",
  "styles/landing.css | .lhelp | gap",
  "styles/landing.css | .lhero | gap",
  "styles/landing.css | .lhpic figcaption | gap",
  "styles/landing.css | .lhpic figcaption>span:not(.gnum) | gap",
  "styles/landing.css | .lhpic | background",
  "styles/landing.css | .lhpic | gap",
  "styles/landing.css | .lmiss .bad b::after | background",
  "styles/landing.css | .lmiss .bad b::after | border-radius",
  "styles/landing.css | .lmiss .bad | background",
  "styles/landing.css | .lmiss .bad | gap",
  "styles/landing.css | .lmiss .good | background",
  "styles/landing.css | .lmiss .good | gap",
  "styles/landing.css | .lmiss .q | gap",
  "styles/landing.css | .lmiss | gap",
  "styles/landing.css | .lone | gap",
  "styles/landing.css | .lonelist li | gap",
  "styles/landing.css | .lonelist li.on | background",
  "styles/landing.css | .lonelist li>span:not(.gnum) | gap",
  "styles/landing.css | .lonelist | gap",
  "styles/landing.css | .lonepic .lsd.out | background",
  "styles/landing.css | .lonepic figcaption | gap",
  "styles/landing.css | .lonepic figcaption>span:not(.gnum) | gap",
  "styles/landing.css | .lonepic | background",
  "styles/landing.css | .lonepic | gap",
  "styles/landing.css | .lreport i | background",
  "styles/landing.css | .lreport i::after | background",
  "styles/landing.css | .lreport | gap",
  "styles/landing.css | .lreport>div | gap",
  "styles/landing.css | .lreview span | background",
  "styles/landing.css | .lreview span | border-radius",
  "styles/landing.css | .lsec | gap",
  "styles/landing.css | .lsteps .q | gap",
  "styles/landing.css | .lsteps .sum | background",
  "styles/landing.css | .lsteps | gap",
  "styles/landing.css | .lsteps>div:not(.q) | background",
  "styles/landing.css | .lsteps>div:not(.q) | gap",
  "styles/landing.css | .ltoday li | background",
  "styles/landing.css | .ltoday li | gap",
  "styles/landing.css | .ltoday li.done .lmark | background",
  "styles/landing.css | .ltoday li.now | background",
  "styles/landing.css | .ltoday li>span:last-child | gap",
  "styles/landing.css | .ltoday | gap",
  "styles/mybento.css | .bmine | gap",
  "styles/mybento.css | .cbat i | background",
  "styles/mybento.css | .cbat i | border-radius",
  "styles/mybento.css | .cbat | border-radius",
  "styles/mybento.css | .cbat | gap",
  "styles/mybento.css | .cbat::after | background",
  "styles/mybento.css | .cbat::after | border-radius",
  "styles/mybento.css | .mych-score | gap",
  "styles/mybento.css | .mych-score>span:not(.cbat) | gap",
  "styles/mybento.css | .mygl li | background",
  "styles/mybento.css | .mygl li | gap",
  "styles/mybento.css | .mygl li>span:last-child | gap",
  "styles/mybento.css | .mygl | gap",
  "styles/mybento.css | .myh-text | gap",
  "styles/mybento.css | .myhero | gap",
  "styles/mybento.css | .myhero>.myh-text:only-child | gap",
  "styles/mybento.css | .mystat | gap",
  "styles/mybento.css | .mytile .ctl:not(.go) | background",
  "styles/mybento.css | .mytile .k | gap",
  "styles/mybento.css | .mytile | gap",
  "styles/nav.css | .battery>.fill | background",
  "styles/nav.css | .bhome .b-stats.battery | gap",
  "styles/nav.css | .book | background",
  "styles/nav.css | .book | border-radius",
  "styles/nav.css | .book | gap",
  "styles/nav.css | .cover | gap",
  "styles/nav.css | .fpill .sw | background",
  "styles/nav.css | .fpill .sw::after | background",
  "styles/nav.css | .fpill | background",
  "styles/nav.css | .fpill | gap",
  "styles/nav.css | .fpill.fb-bad | background",
  "styles/nav.css | .fpill.fb-good | background",
  "styles/nav.css | .fpill.fb-hint | background",
  "styles/nav.css | .fpill[aria-checked=\"true\"] .sw | background",
  "styles/nav.css | .fstack | gap",
  "styles/nav.css | .halo | background",
  "styles/nav.css | .icon | background",
  "styles/nav.css | .icon.on | background",
  "styles/nav.css | .icon:active | background",
  "styles/nav.css | .icon:hover | background",
  "styles/nav.css | .icorner | gap",
  "styles/nav.css | .imine | background",
  "styles/nav.css | .iresume .rdot | background",
  "styles/nav.css | .iresume | background",
  "styles/nav.css | .iresume | gap",
  "styles/nav.css | .iresume-x | background",
  "styles/nav.css | .island .iback | background",
  "styles/nav.css | .island .iback:active | background",
  "styles/nav.css | .island .iback:hover | background",
  "styles/nav.css | .island .ibat | background",
  "styles/nav.css | .island | background",
  "styles/nav.css | .island | gap",
  "styles/nav.css | .island:not(.guest) | gap",
  "styles/nav.css | .itop | gap",
  "styles/nav.css | .itop:has(>.icorner.left) | gap",
  "styles/nav.css | .lbar .dots-nav button.dot:not(:disabled):active | background",
  "styles/nav.css | .lbar .dots-nav button.dot:not(:disabled):hover | background",
  "styles/nav.css | .mhero.battery | background",
  "styles/nav.css | .sbooks | gap",
  "styles/nav.css | .sheet .shelf | column-gap",
  "styles/nav.css | .shelf | gap",
  "styles/nav.css | .sline | gap",
  "styles/nav.css | .zbar-top | gap",
  "styles/nav.css | .zcard | background",
  "styles/nav.css | .zcard | border-radius",
  "styles/nav.css | .zcard | gap",
  "styles/nav.css | .zch | gap",
  "styles/nav.css | .zchapter | background",
  "styles/nav.css | .zchapter | gap",
  "styles/nav.css | .zclose | background",
  "styles/nav.css | .zctext | gap",
  "styles/nav.css | .zoom | background",
  "styles/nav.css | .zoom | gap",
  "styles/nav.css | .zpages .pn | background",
  "styles/nav.css | .zpages button | gap",
  "styles/nav.css | .zpages button.on .pn | background",
  "styles/nav.css | .zpages button.on | background",
  "styles/nav.css | .zpages button:active:not(:disabled) | background",
  "styles/nav.css | .zpages button:hover:not(:disabled) | background",
  "styles/nav.css | .zpages | gap",
  "styles/nav.css | .zshelf .shelf | column-gap",
  "styles/nav.css | .zshelf | gap",
  "styles/nav.css | .zyear | gap",
  "styles/nav.css | .zyear>header | gap",
  "styles/screen.css | .bhome .today .ctl:not(.go) | background",
  "styles/screen.css | .bhome .today .pitem:active | background",
  "styles/screen.css | .bhome .today .pitem:hover | background",
  "styles/screen.css | .bhome .today | background",
  "styles/screen.css | .bhome.sbento :is(.b-stats,.b-streak) | gap",
  "styles/screen.css | .fhome>.bhome | gap",
  "styles/screen.css | .gbtn | background",
  "styles/screen.css | .gbtn:active | background",
  "styles/screen.css | .gbtn:hover | background",
  "styles/screen.css | .gq | gap",
  "styles/screen.css | .gqhead | gap",
  "styles/screen.css | .gstrip | gap",
  "styles/screen.css | .gstrip | row-gap",
  "styles/screen.css | .gychips li | background",
  "styles/screen.css | .gychips | gap",
  "styles/screen.css | .gypic | background",
  "styles/screen.css | .gypic | gap",
  "styles/screen.css | .gytext | background",
  "styles/screen.css | .gytext | gap",
  "styles/screen.css | .icon.ihint.on .ibadge | background",
  "styles/screen.css | .icon.ihint.on | background",
  "styles/screen.css | .ihint .ibadge | background",
  "styles/screen.css | .lctl .ctl | background",
  "styles/screen.css | .lctl .ctl.go | background",
  "styles/screen.css | .lctl | gap",
  "styles/screen.css | .ldots i | background",
  "styles/screen.css | .ldots i | border-radius",
  "styles/screen.css | .ldots i.done | background",
  "styles/screen.css | .ldots | background",
  "styles/screen.css | .ldots | gap",
  "styles/screen.css | .lintro .beat .badge | background",
  "styles/screen.css | .lintro .beat .say | gap",
  "styles/screen.css | .lintro .beat | border-radius",
  "styles/screen.css | .lintro .beat>button | border-radius",
  "styles/screen.css | .lintro .beat>button | gap",
  "styles/screen.css | .lintro .beat>button:not([disabled]):hover | background",
  "styles/screen.css | .lintro .beat[data-state=\"now\"] .badge | background",
  "styles/screen.css | .lintro .beat[data-state=\"now\"] | background",
  "styles/screen.css | .lintro .beats | background",
  "styles/screen.css | .lintro .beats | border-radius",
  "styles/screen.css | .lintro .beats | gap",
  "styles/screen.css | .lintro .k | gap",
  "styles/screen.css | .lintro | background",
  "styles/screen.css | .lintro | gap",
  "styles/screen.css | .lmath .mline | row-gap",
  "styles/screen.css | .lmath | gap",
  "styles/screen.css | .lnow>p | gap",
  "styles/screen.css | .lshero | background",
  "styles/screen.css | .lshero | gap",
  "styles/screen.css | .lshero.phero | gap",
  "styles/screen.css | .lshero.phero>.pfb | border-radius",
  "styles/screen.css | .lshero.phero>.pfb:is(.fb-bad,.fb-good,.fb-hint) | background",
  "styles/screen.css | .panel.split .actions .ctl | background",
  "styles/screen.css | .panel.split .card | background",
  "styles/screen.css | .panel.split .card | gap",
  "styles/screen.css | .panel.split .tray button | background",
  "styles/screen.css | .panel.split .tray button:active | background",
  "styles/screen.css | .panel.split .tray button:hover | background",
  "styles/screen.css | .pbeats .badge | background",
  "styles/screen.css | .pbeats .beat | gap",
  "styles/screen.css | .pbeats .beat[data-state=\"now\"] .badge | background",
  "styles/screen.css | .pbeats .beat[data-state=\"now\"] | background",
  "styles/screen.css | .pbeats .say | gap",
  "styles/screen.css | .pbeats | gap",
  "styles/screen.css | .pdots i | background",
  "styles/screen.css | .pdots i | border-radius",
  "styles/screen.css | .pdots i.now | background",
  "styles/screen.css | .pdots i.ok | background",
  "styles/screen.css | .pdots | gap",
  "styles/screen.css | .pextra .ctl | background",
  "styles/screen.css | .pextra | gap",
  "styles/screen.css | .pfb .dot | border-radius",
  "styles/screen.css | .pfb | gap",
  "styles/screen.css | .pintro | gap",
  "styles/screen.css | .pmath .ask.ok .ans | border-radius",
  "styles/screen.css | .pmath | gap",
  "styles/screen.css | .pprob | gap",
  "styles/screen.css | .pscreen .fstack .fpill.go | background",
  "styles/screen.css | .pscreen .hrow | gap",
  "styles/screen.css | .pscreen .lshero.phero::before | background",
  "styles/screen.css | .pscreen .lshero.phero::before | border-radius",
  "styles/screen.css | .pscreen .lshero.phero>.phint | background",
  "styles/screen.css | .pscreen .lshero.phero>.phint | gap",
  "styles/screen.css | .pscreen .pbar .chev | background",
  "styles/screen.css | .pscreen .pbar .hrow | gap",
  "styles/screen.css | .pscreen .pbar .pstep .badge | background",
  "styles/screen.css | .pscreen .pbar .pstep .sname | gap",
  "styles/screen.css | .pscreen .pbar .pstep.on .badge | background",
  "styles/screen.css | .pscreen .pbar .pwhere | gap",
  "styles/screen.css | .pscreen .pbar .sgroup.open>.srow.chap | background",
  "styles/screen.css | .pscreen .pbar .srow | border-radius",
  "styles/screen.css | .pscreen .pbar .srow | gap",
  "styles/screen.css | .pscreen .pbar .srow.chap | background",
  "styles/screen.css | .pscreen .pbar .srow.chap | border-radius",
  "styles/screen.css | .pscreen.nopic .pmath | gap",
  "styles/screen.css | .pscreen>.lpic | background",
  "styles/screen.css | .pscreen>.lpic | border-radius",
  "styles/screen.css | .pscreen>.ppad .choice | border-radius",
  "styles/screen.css | .pscreen>.ppad .choice:not(.ok,.no) | background",
  "styles/screen.css | .pscreen>.ppad .choice:not(.ok,.no):is(:hover,:active) | background",
  "styles/screen.css | .pscreen>.ppad .tray button:not(.k-go) | background",
  "styles/screen.css | .pscreen>.ppad .tray button:not(.k-go):is(:hover,:active) | background",
  "styles/screen.css | .pscreen>.ppad .tray>* | border-radius",
  "styles/screen.css | .pscreen>.ppad | background",
  "styles/screen.css | .psteps .ctl | background",
  "styles/screen.css | .psteps .pwhere | gap",
  "styles/screen.css | .rscreen>.rsum | gap",
  "styles/screen.css | .sbento .b-streak | background",
  "styles/screen.css | .sbento .b-streak | gap",
  "styles/screen.css | .sbento :is(.b-stats,.b-streak) | gap",
  "styles/screen.css | .screen .slist | background",
  "styles/screen.css | .sdtext | background",
  "styles/screen.css | .sdtext | gap",
  "styles/screen.css | .sfoot | background",
  "styles/screen.css | .sfootrow .ctl:not(.go) | background",
  "styles/screen.css | .sfootrow .ctl:not(.go):active | background",
  "styles/screen.css | .sfootrow .ctl:not(.go):hover | background",
  "styles/screen.css | .sfootrow .slast | gap",
  "styles/screen.css | .sfootrow | gap",
  "styles/screen.css | .sgroup .srow.sles:not([disabled]):not(.on):active | background",
  "styles/screen.css | .sgroup .srow.sles:not([disabled]):not(.on):hover | background",
  "styles/screen.css | .slist .ctl:not(.go) | background",
  "styles/screen.css | .slist .ctl:not(.go):active | background",
  "styles/screen.css | .slist .ctl:not(.go):hover | background",
  "styles/screen.css | .slist .shead:has(.scheck) | gap",
  "styles/screen.css | .spreview figcaption | gap",
  "styles/screen.css | .spreview | background",
  "styles/screen.css | .srow.chap.holds .sname b::after | background",
  "styles/screen.css | .whead>.ctl | background",
  "styles/screen.css | .wpad .tray | gap",
  "styles/screen.css | .wrap .sdetail>.bhome.sbento .today | column-gap",
  "styles/screen.css | .wrap .sdetail>.bhome.sbento .today | row-gap",
  "styles/screen.css | .wrap.gyin | gap",
  "styles/screens.css | .lesson.soon | background",
  "styles/screens.css | .lesson.soon:active | background",
  "styles/screens.css | .lesson.soon:hover | background",
  "styles/screens.css | .lesson[disabled]:not(.soon):active | background",
  "styles/screens.css | .lesson[disabled]:not(.soon):hover | background",
  "styles/settings.css | .bset | gap",
  "styles/settings.css | .snote | gap",
];
