// The curriculum in the current app's order: grade, then unit, then lesson. Lesson ids are stable because saved progress uses them.
// Each entry is implemented by a lesson module at lessons/<grade>/<id>/index.ts exporting `lesson`;
// the parity tests check every module matches its entry and the current app's behaviour.
export interface CatalogEntry {
  id: string;
  grade: number;
  unit: string;
  title: string;
  /** "Build up first" lesson, when the current app names one */
  pre: string | null;
  /** which steps make the final answer (the current app's FINAL table) */
  final: number[];
}

export const CATALOG: CatalogEntry[] = [
  { id: "k-count20", grade: 0, unit: "Counting", title: "Count to 20", pre: null, final: [-1] },
  { id: "k-write", grade: 0, unit: "Counting", title: "Write numbers 0 to 20", pre: "k-count20", final: [-1] },
  { id: "k-tens", grade: 0, unit: "Counting", title: "Count by tens to 100", pre: "k-count20", final: [-1] },
  { id: "k-teens", grade: 0, unit: "Counting", title: "Teen numbers", pre: "k-count20", final: [-1] },
  { id: "k-compare", grade: 0, unit: "Counting", title: "More, less or the same", pre: "k-count20", final: [-1] },
  { id: "k-add", grade: 0, unit: "Adding and subtracting", title: "Adding within 10", pre: null, final: [-1] },
  { id: "k-sub", grade: 0, unit: "Adding and subtracting", title: "Taking away within 10", pre: "k-add", final: [-1] },
  { id: "k-make10", grade: 0, unit: "Adding and subtracting", title: "Make 10", pre: "k-add", final: [-1] },
  { id: "k-bonds", grade: 0, unit: "Adding and subtracting", title: "Number bonds", pre: "k-add", final: [-1] },
  { id: "k-story", grade: 0, unit: "Adding and subtracting", title: "Story problems within 10", pre: "k-add", final: [-1] },
  { id: "k-shapes", grade: 0, unit: "Shapes and measuring", title: "Flat shapes", pre: null, final: [-1] },
  { id: "k-solids", grade: 0, unit: "Shapes and measuring", title: "Solid shapes", pre: "k-shapes", final: [-1] },
  { id: "k-length", grade: 0, unit: "Shapes and measuring", title: "Longer and shorter", pre: null, final: [-1] },
  { id: "k-sort", grade: 0, unit: "Shapes and measuring", title: "Sort and count", pre: "k-compare", final: [-1] },
  { id: "g1-tensones", grade: 1, unit: "Place value", title: "Tens and ones", pre: "k-teens", final: [-1] },
  { id: "g1-compare", grade: 1, unit: "Place value", title: "Compare two-digit numbers", pre: "g1-tensones", final: [-1] },
  { id: "g1-tenmore", grade: 1, unit: "Place value", title: "10 more, 10 less", pre: "g1-tensones", final: [-1] },
  { id: "g1-ten", grade: 1, unit: "Adding and subtracting", title: "Make a ten to add", pre: null, final: [-1] },
  { id: "g1-add20", grade: 1, unit: "Adding and subtracting", title: "Add within 20", pre: "g1-ten", final: [-1] },
  { id: "g1-three", grade: 1, unit: "Adding and subtracting", title: "Add three numbers", pre: "g1-ten", final: [-1] },
  { id: "g1-sub20", grade: 1, unit: "Adding and subtracting", title: "Subtract within 20", pre: "k-sub", final: [-1] },
  { id: "g1-missing", grade: 1, unit: "Adding and subtracting", title: "Missing numbers", pre: "g1-sub20", final: [-1] },
  { id: "g1-addtens", grade: 1, unit: "Adding and subtracting", title: "Add tens to a number", pre: "g1-tenmore", final: [-1] },
  { id: "g1-time", grade: 1, unit: "Measurement and shapes", title: "Time to the hour and half hour", pre: null, final: [-1] },
  { id: "g1-measure", grade: 1, unit: "Measurement and shapes", title: "Measure length", pre: "k-length", final: [-1] },
  { id: "g1-halves", grade: 1, unit: "Measurement and shapes", title: "Halves and fourths", pre: "k-shapes", final: [-1] },
  { id: "g1-tally", grade: 1, unit: "Data", title: "Tally charts", pre: "k-sort", final: [-1] },
  { id: "g1-picgraph", grade: 1, unit: "Data", title: "Picture graphs", pre: "g1-tally", final: [-1] },
  { id: "g2-hundreds", grade: 2, unit: "Place value", title: "Hundreds, tens and ones", pre: "g1-tensones", final: [-1] },
  { id: "g2-skip", grade: 2, unit: "Place value", title: "Skip counting", pre: "k-tens", final: [-1] },
  { id: "g2-evenodd", grade: 2, unit: "Place value", title: "Even and odd", pre: null, final: [-1] },
  { id: "g2-regroup", grade: 2, unit: "Adding and subtracting", title: "Adding with regrouping", pre: null, final: [-1] },
  { id: "g2-subregroup", grade: 2, unit: "Adding and subtracting", title: "Subtracting with regrouping", pre: "g1-sub20", final: [-1] },
  { id: "g2-within1000", grade: 2, unit: "Adding and subtracting", title: "Add and subtract within 1000", pre: "g2-regroup", final: [-1] },
  { id: "g2-coins", grade: 2, unit: "Measurement and data", title: "Name the coin", pre: null, final: [-1] },
  { id: "g2-money", grade: 2, unit: "Measurement and data", title: "Counting money", pre: "g2-skip", final: [-1] },
  { id: "g2-time5", grade: 2, unit: "Measurement and data", title: "Time to 5 minutes", pre: "g1-time", final: [-1] },
  { id: "g2-measure", grade: 2, unit: "Measurement and data", title: "Inches and centimeters", pre: "g1-measure", final: [-1] },
  { id: "g2-estimate", grade: 2, unit: "Measurement and data", title: "Estimate length", pre: "g2-measure", final: [0, 1] },
  { id: "g2-bargraph", grade: 2, unit: "Measurement and data", title: "Bar graphs", pre: null, final: [-1] },
  { id: "g2-lineplot", grade: 2, unit: "Measurement and data", title: "Line plots", pre: "g2-measure", final: [-1] },
  { id: "g2-arrays", grade: 2, unit: "Getting ready to multiply", title: "Arrays", pre: "g2-skip", final: [-1] },
  { id: "g2-solids", grade: 2, unit: "Shapes", title: "Faces, edges and corners", pre: "k-solids", final: [-1, 0] },
  { id: "g2-shares", grade: 2, unit: "Shapes", title: "Halves, thirds and fourths", pre: "g1-halves", final: [-3, -2] },
  { id: "g3-split", grade: 3, unit: "Multiplication and division", title: "Multiply by breaking apart", pre: null, final: [-1] },
  { id: "g3-facts", grade: 3, unit: "Multiplication and division", title: "Multiplication facts", pre: "g2-arrays", final: [-1] },
  { id: "g3-divfacts", grade: 3, unit: "Multiplication and division", title: "Division facts", pre: "g3-facts", final: [-1] },
  { id: "g3-mult10", grade: 3, unit: "Multiplication and division", title: "Multiply by multiples of 10", pre: "g3-facts", final: [-1] },
  { id: "g3-twostep", grade: 3, unit: "Multiplication and division", title: "Two-step word problems", pre: "g3-facts", final: [-1] },
  { id: "g3-round", grade: 3, unit: "Place value", title: "Rounding to 10 and 100", pre: "g2-hundreds", final: [-1] },
  { id: "g3-addsub", grade: 3, unit: "Place value", title: "Add and subtract within 1000", pre: "g2-within1000", final: [-1] },
  { id: "g3-unitfrac", grade: 3, unit: "Fractions", title: "Unit fractions", pre: "g1-halves", final: [-1] },
  { id: "g3-fracline", grade: 3, unit: "Fractions", title: "Fractions on a number line", pre: "g3-unitfrac", final: [-1] },
  { id: "g3-fraccompare", grade: 3, unit: "Fractions", title: "Comparing fractions", pre: "g3-unitfrac", final: [-1] },
  { id: "g3-area", grade: 3, unit: "Measurement", title: "Area by counting squares", pre: "g2-arrays", final: [-1] },
  { id: "g3-perim", grade: 3, unit: "Measurement", title: "Perimeter", pre: null, final: [-1] },
  { id: "g3-elapsed", grade: 3, unit: "Measurement", title: "Elapsed time", pre: "g2-time5", final: [-1] },
  { id: "g3-mass", grade: 3, unit: "Measurement", title: "Grams and kilograms", pre: "g3-addsub", final: [-1] },
  { id: "g3-liters", grade: 3, unit: "Measurement", title: "Liters", pre: "g3-mass", final: [-1] },
  { id: "g3-graphs", grade: 3, unit: "Data", title: "Scaled picture and bar graphs", pre: "g2-bargraph", final: [-1] },
  { id: "g3-lineplot", grade: 3, unit: "Data", title: "Line plots with halves and fourths", pre: "g2-lineplot", final: [-1] },
  { id: "g3-quads", grade: 3, unit: "Shapes", title: "Quadrilaterals", pre: "k-shapes", final: [-1] },
  { id: "g4-placevalue", grade: 4, unit: "Whole numbers", title: "Place value and rounding", pre: "g3-round", final: [-1] },
  { id: "g4-addsub", grade: 4, unit: "Whole numbers", title: "Add and subtract big numbers", pre: "g3-addsub", final: [-1] },
  { id: "g4-partial", grade: 4, unit: "Whole numbers", title: "Multiply big numbers", pre: "g3-split", final: [-1] },
  { id: "g4-mult2x2", grade: 4, unit: "Whole numbers", title: "Two-digit times two-digit", pre: "g4-partial", final: [-1] },
  { id: "g4-divide", grade: 4, unit: "Whole numbers", title: "Dividing with remainders", pre: null, final: [-2, -1] },
  { id: "g4-factors", grade: 4, unit: "Whole numbers", title: "Factors and multiples", pre: "g3-facts", final: [-1] },
  { id: "g4-equiv", grade: 4, unit: "Fractions", title: "Equivalent fractions", pre: null, final: [-1] },
  { id: "g4-likefrac", grade: 4, unit: "Fractions", title: "Adding like fractions", pre: "g4-equiv", final: [-1] },
  { id: "g4-fraccompare", grade: 4, unit: "Fractions", title: "Comparing fractions", pre: "g4-equiv", final: [-1] },
  { id: "g4-mixed", grade: 4, unit: "Fractions", title: "Adding mixed numbers", pre: "g4-likefrac", final: [-1] },
  { id: "g4-fracwhole", grade: 4, unit: "Fractions", title: "Fraction times a whole number", pre: null, final: [-1] },
  { id: "g4-dec", grade: 4, unit: "Decimals", title: "Tenths and hundredths", pre: null, final: [-1] },
  { id: "g4-deccompare", grade: 4, unit: "Decimals", title: "Comparing decimals", pre: "g4-dec", final: [-1] },
  { id: "g4-convert", grade: 4, unit: "Measurement", title: "Converting measurements", pre: null, final: [-1] },
  { id: "g4-lineplot", grade: 4, unit: "Measurement", title: "Line plots with fractions", pre: "g3-lineplot", final: [-1] },
  { id: "g4-area", grade: 4, unit: "Measurement", title: "Area and perimeter", pre: null, final: [0, -1] },
  { id: "g4-angles", grade: 4, unit: "Measurement", title: "Angles add up", pre: null, final: [-1] },
  { id: "g4-lines", grade: 4, unit: "Lines and shapes", title: "Points, lines, rays and angles", pre: "g4-angles", final: [-1] },
  { id: "g4-symmetry", grade: 4, unit: "Lines and shapes", title: "Lines of symmetry", pre: "g4-lines", final: [-1] },
  { id: "g5-mult2", grade: 5, unit: "Whole numbers", title: "Multiply two-digit numbers", pre: "g4-partial", final: [-1] },
  { id: "g5-divide", grade: 5, unit: "Whole numbers", title: "Long division", pre: "g4-divide", final: [-1] },
  { id: "g5-order", grade: 5, unit: "Whole numbers", title: "Order of operations", pre: "g5-mult2", final: [-1] },
  { id: "g5-pow10", grade: 5, unit: "Decimals", title: "Multiply by 10, 100, 1000", pre: null, final: [-1] },
  { id: "g5-round", grade: 5, unit: "Decimals", title: "Rounding decimals", pre: "g4-dec", final: [-1] },
  { id: "g5-adddec", grade: 5, unit: "Decimals", title: "Adding decimals", pre: "g4-dec", final: [-1] },
  { id: "g5-multdec", grade: 5, unit: "Decimals", title: "Multiplying decimals", pre: "g5-mult2", final: [-1] },
  { id: "g5-divdec", grade: 5, unit: "Decimals", title: "Dividing by a decimal", pre: "g5-divide", final: [-1] },
  { id: "add", grade: 5, unit: "Fractions", title: "Adding fractions", pre: "g4-likefrac", final: [-1] },
  { id: "sub", grade: 5, unit: "Fractions", title: "Subtracting fractions", pre: "g4-likefrac", final: [-1] },
  { id: "mix", grade: 5, unit: "Fractions", title: "Adding and subtracting", pre: "add", final: [-1] },
  { id: "g5-multfrac", grade: 5, unit: "Fractions", title: "Multiplying fractions", pre: "g4-fracwhole", final: [-1] },
  { id: "g5-improper", grade: 5, unit: "Fractions", title: "Mixed numbers to fractions", pre: "g4-equiv", final: [-1] },
  { id: "g5-fracof", grade: 5, unit: "Fractions", title: "Fraction of a number", pre: "g4-fracwhole", final: [-1] },
  { id: "g5-unitdiv", grade: 5, unit: "Fractions", title: "Dividing by a unit fraction", pre: "g5-fracof", final: [-1] },
  { id: "g5-volume", grade: 5, unit: "Measurement", title: "Volume of a box", pre: "g4-area", final: [-1] },
  { id: "g5-units", grade: 5, unit: "Measurement", title: "Converting units", pre: null, final: [-1] },
  { id: "g6-ratio", grade: 6, unit: "Ratios and percents", title: "Equivalent ratios", pre: null, final: [-1] },
  { id: "g6-rate", grade: 6, unit: "Ratios and percents", title: "Unit rates", pre: "g5-divide", final: [-1] },
  { id: "g6-pctof", grade: 6, unit: "Ratios and percents", title: "Percent of a number", pre: "g5-fracof", final: [-1] },
  { id: "g6-pctwhole", grade: 6, unit: "Ratios and percents", title: "Find the whole", pre: null, final: [-1] },
  { id: "g6-divide", grade: 6, unit: "Number system", title: "Dividing fractions", pre: "g5-multfrac", final: [-1] },
  { id: "g6-gcf", grade: 6, unit: "Number system", title: "Factor out the GCF", pre: null, final: [-1] },
  { id: "g6-lcm", grade: 6, unit: "Number system", title: "Least common multiple", pre: null, final: [0] },
  { id: "g6-numline", grade: 6, unit: "Number system", title: "Distance on a number line", pre: null, final: [-1] },
  { id: "g6-expo", grade: 6, unit: "Expressions and equations", title: "Exponents and order", pre: null, final: [-1] },
  { id: "g6-eval", grade: 6, unit: "Expressions and equations", title: "Evaluate expressions", pre: null, final: [-1] },
  { id: "g6-onestep", grade: 6, unit: "Expressions and equations", title: "One-step equations", pre: "g5-order", final: [0] },
  { id: "g6-tri", grade: 6, unit: "Geometry", title: "Area of a triangle", pre: "g4-area", final: [-1] },
  { id: "g6-trap", grade: 6, unit: "Geometry", title: "Area of a trapezoid", pre: "g6-tri", final: [-1] },
  { id: "g6-mean", grade: 6, unit: "Statistics", title: "Find the mean", pre: null, final: [-1] },
  { id: "g7-prop", grade: 7, unit: "Proportions and percents", title: "Solve a proportion", pre: null, final: [-1] },
  { id: "g7-scale", grade: 7, unit: "Proportions and percents", title: "Scale drawings", pre: null, final: [-1] },
  { id: "g7-discount", grade: 7, unit: "Proportions and percents", title: "Discounts, tax and tips", pre: null, final: [-1] },
  { id: "g7-pctchange", grade: 7, unit: "Proportions and percents", title: "Percent change", pre: null, final: [-1] },
  { id: "g7-addint", grade: 7, unit: "Integers", title: "Adding integers", pre: null, final: [-1] },
  { id: "g7-subint", grade: 7, unit: "Integers", title: "Subtracting integers", pre: null, final: [-1] },
  { id: "g7-mulint", grade: 7, unit: "Integers", title: "Multiplying and dividing integers", pre: null, final: [-1] },
  { id: "g7-eq", grade: 7, unit: "Expressions and equations", title: "Two-step equations", pre: "g6-onestep", final: [-1] },
  { id: "g7-distribute", grade: 7, unit: "Expressions and equations", title: "Distribute and combine", pre: null, final: [-1] },
  { id: "g7-circum", grade: 7, unit: "Geometry", title: "Circumference", pre: null, final: [-1] },
  { id: "g7-circarea", grade: 7, unit: "Geometry", title: "Area of a circle", pre: "g6-expo", final: [-1] },
  { id: "g7-angles", grade: 7, unit: "Geometry", title: "Complementary and supplementary", pre: "g4-angles", final: [-1] },
  { id: "g7-prob", grade: 7, unit: "Probability", title: "Probability", pre: null, final: [-1] },
  { id: "g8-exp", grade: 8, unit: "Exponents and roots", title: "Exponent rules", pre: null, final: [0] },
  { id: "g8-sci", grade: 8, unit: "Exponents and roots", title: "Scientific notation", pre: null, final: [-1] },
  { id: "g8-roots", grade: 8, unit: "Exponents and roots", title: "Square and cube roots", pre: null, final: [0] },
  { id: "g8-both", grade: 8, unit: "Linear equations", title: "Variables on both sides", pre: "g7-eq", final: [-1] },
  { id: "g8-system", grade: 8, unit: "Linear equations", title: "Systems by substitution", pre: null, final: [-2, -1] },
  { id: "g8-slope", grade: 8, unit: "Functions and slope", title: "Slope from two points", pre: null, final: [-1] },
  { id: "g8-intercept", grade: 8, unit: "Functions and slope", title: "Slope-intercept form", pre: null, final: [-1] },
  { id: "g8-func", grade: 8, unit: "Functions and slope", title: "Evaluate a function", pre: null, final: [-1] },
  { id: "g8-pyth", grade: 8, unit: "Geometry", title: "Pythagorean theorem", pre: "g8-roots", final: [-1] },
  { id: "g8-leg", grade: 8, unit: "Geometry", title: "Find a missing leg", pre: "g8-pyth", final: [-1] },
  { id: "g8-cyl", grade: 8, unit: "Geometry", title: "Volume of a cylinder", pre: null, final: [-1] },
  { id: "g8-cone", grade: 8, unit: "Geometry", title: "Volume of a cone", pre: null, final: [-1] },
  { id: "g8-translate", grade: 8, unit: "Geometry", title: "Translations", pre: null, final: [-2, -1] },
  { id: "g8-tri", grade: 8, unit: "Geometry", title: "Angles in a triangle", pre: null, final: [-1] },
  { id: "g9-multistep", grade: 9, unit: "Equations", title: "Multi-step equations", pre: "g8-both", final: [-1] },
  { id: "g9-elim", grade: 9, unit: "Equations", title: "Systems by elimination", pre: null, final: [-2, -1] },
  { id: "g9-twopoint", grade: 9, unit: "Linear functions", title: "Line through two points", pre: null, final: [-1] },
  { id: "g9-negexp", grade: 9, unit: "Exponents", title: "Zero and negative exponents", pre: null, final: [-1] },
  { id: "g9-growth", grade: 9, unit: "Exponents", title: "Exponential growth", pre: null, final: [-1] },
  { id: "g9-radical", grade: 9, unit: "Exponents", title: "Simplify square roots", pre: null, final: [-1] },
  { id: "g9-factor", grade: 9, unit: "Polynomials and quadratics", title: "Factoring quadratics", pre: null, final: [-1] },
  { id: "g9-polyadd", grade: 9, unit: "Polynomials and quadratics", title: "Add and subtract polynomials", pre: null, final: [-3, -2, -1] },
  { id: "g9-foil", grade: 9, unit: "Polynomials and quadratics", title: "Multiply binomials", pre: null, final: [-1] },
  { id: "g9-gcf", grade: 9, unit: "Polynomials and quadratics", title: "Factor out the GCF", pre: null, final: [-1] },
  { id: "g9-solvefactor", grade: 9, unit: "Polynomials and quadratics", title: "Solve by factoring", pre: null, final: [-1] },
  { id: "g9-quadform", grade: 9, unit: "Polynomials and quadratics", title: "The quadratic formula", pre: null, final: [-1] },
  { id: "g9-median", grade: 9, unit: "Data", title: "Find the median", pre: null, final: [-1] },
  { id: "g10-mid", grade: 10, unit: "Coordinate geometry", title: "Midpoint", pre: null, final: [-2, -1] },
  { id: "g10-perp", grade: 10, unit: "Coordinate geometry", title: "Perpendicular slopes", pre: null, final: [-1] },
  { id: "g10-dist", grade: 10, unit: "Coordinate geometry", title: "Distance between points", pre: null, final: [-1] },
  { id: "g10-circle", grade: 10, unit: "Coordinate geometry", title: "Equation of a circle", pre: null, final: [-2, -1] },
  { id: "g10-polygon", grade: 10, unit: "Angles and triangles", title: "Angles in a polygon", pre: null, final: [-1] },
  { id: "g10-exterior", grade: 10, unit: "Angles and triangles", title: "Exterior angle", pre: null, final: [-1] },
  { id: "g10-similar", grade: 10, unit: "Angles and triangles", title: "Similar triangles", pre: null, final: [-1] },
  { id: "g10-special", grade: 10, unit: "Right triangles and trig", title: "Special right triangles", pre: null, final: [-1] },
  { id: "g10-trig", grade: 10, unit: "Right triangles and trig", title: "Sine, cosine and tangent", pre: null, final: [-1] },
  { id: "g10-sector", grade: 10, unit: "Circles", title: "Area of a sector", pre: null, final: [-1] },
  { id: "g10-arc", grade: 10, unit: "Circles", title: "Arc length", pre: null, final: [-1] },
  { id: "g10-surface", grade: 10, unit: "Area and volume", title: "Surface area of a box", pre: null, final: [-1] },
  { id: "g10-pyramid", grade: 10, unit: "Area and volume", title: "Volume of a pyramid", pre: null, final: [-1] },
  { id: "g11-seq", grade: 11, unit: "Sequences", title: "Arithmetic sequences", pre: null, final: [-1] },
  { id: "g11-geo", grade: 11, unit: "Sequences", title: "Geometric sequences", pre: null, final: [-1] },
  { id: "g11-log", grade: 11, unit: "Exponents and logs", title: "Evaluating logarithms", pre: null, final: [-1] },
  { id: "g11-expeq", grade: 11, unit: "Exponents and logs", title: "Exponential equations", pre: null, final: [-1] },
  { id: "g11-ratexp", grade: 11, unit: "Exponents and logs", title: "Rational exponents", pre: null, final: [-1] },
  { id: "g11-evalpoly", grade: 11, unit: "Polynomials", title: "Evaluate a polynomial", pre: null, final: [-1] },
  { id: "g11-synth", grade: 11, unit: "Polynomials", title: "Synthetic division", pre: null, final: [-1] },
  { id: "g11-inverse", grade: 11, unit: "Functions", title: "Inverse functions", pre: null, final: [-1] },
  { id: "g11-compose", grade: 11, unit: "Functions", title: "Composing functions", pre: null, final: [-1] },
  { id: "g11-vertex", grade: 11, unit: "Functions", title: "Vertex of a parabola", pre: null, final: [-2, -1] },
  { id: "g11-radical", grade: 11, unit: "Functions", title: "Radical equations", pre: null, final: [-1] },
  { id: "g11-complex", grade: 11, unit: "Complex numbers", title: "Multiplying complex numbers", pre: null, final: [-2, -1] },
  { id: "g11-comb", grade: 11, unit: "Probability", title: "Combinations", pre: null, final: [-1] },
  { id: "g12-rad", grade: 12, unit: "Trigonometry", title: "Degrees to radians", pre: null, final: [-1] },
  { id: "g12-deg", grade: 12, unit: "Trigonometry", title: "Radians to degrees", pre: null, final: [-1] },
  { id: "g12-unit", grade: 12, unit: "Trigonometry", title: "Unit circle values", pre: null, final: [-1] },
  { id: "g12-limit", grade: 12, unit: "Limits", title: "Limits by factoring", pre: null, final: [-1] },
  { id: "g12-power", grade: 12, unit: "Derivatives", title: "Power rule", pre: null, final: [-1] },
  { id: "g12-polyd", grade: 12, unit: "Derivatives", title: "Derivative of a polynomial", pre: null, final: [-1] },
  { id: "g12-chain", grade: 12, unit: "Derivatives", title: "Chain rule", pre: null, final: [-1] },
  { id: "g12-tangent", grade: 12, unit: "Derivatives", title: "Slope of a tangent line", pre: null, final: [-1] },
  { id: "g12-anti", grade: 12, unit: "Integrals", title: "Antiderivatives", pre: null, final: [-2, -1] },
  { id: "g12-defint", grade: 12, unit: "Integrals", title: "Definite integrals", pre: null, final: [-1] },
  { id: "g12-series", grade: 12, unit: "Vectors and series", title: "Arithmetic series", pre: null, final: [-1] },
  { id: "g12-vecmag", grade: 12, unit: "Vectors and series", title: "Vector length", pre: null, final: [-1] },
  { id: "g12-dot", grade: 12, unit: "Vectors and series", title: "Dot product", pre: null, final: [-1] },
];
