// The early grades now have full years, so their single lessons moved from "Skills" into real units (G, 2026-10-03).
export const deviations: Record<string, Partial<Record<string, string>>> = {
  "k-add": { unit: "kindergarten has units now; this lesson lives in Adding and subtracting", hint: "\"There is 1 dot\", not \"There are 1 dot\" (Curriculum fixes-01, 2026-10-03)", explain: "same wording fix as the hint",
    checks: "\"Count the first group\" names three more slips (counted both groups, one too many, one short) instead of the generic nudge (Curriculum fixes-02 Part C, K-3 pattern 3: steps with no named slip, 2026-10-06)" },
  "g1-ten": { unit: "1st grade has units now; this lesson lives in Adding and subtracting",
    pre: "builds up from k-make10: filling a ten frame is the step this lesson leans on (Curriculum fixes-02, K-3 g1-ten and Order 2, 2026-10-06)",
    checks: "\"Make a ten\" names typing 10 (the full frame) and the dots already there; \"Break apart\" names keeping all of the second number; \"Forgot the ten\" says why instead of \"Don't forget the 10!\" (Curriculum fixes-02, K-3 g1-ten rewrite, 2026-10-06)" },
  "g2-regroup": { unit: "2nd grade has units now; this lesson lives in Adding and subtracting",
    hint: "the ones and tens hints name the problem's own digits, \"Add just the ones: 7 + 8.\" (Review v40 little things 4: hints use the live numbers, 2026-10-06); then the fixes-02 rewrite: \"Add the ones cubes: 8 + 9.\", \"17 ones is too many for the ones place. Trade 10 of them for 1 ten rod...\", \"Count the ten rods: 4 + 4, plus the new rod you made.\"",
    checks: "a wrong try's message repeats the step's hint, so it names the digits too (same review item)",
    pre: "builds up from g1-addtens: adding tens to a number comes before trading ones for a ten (Curriculum fixes-02, K-3 g2-regroup and Order 5, 2026-10-06)",
    prompt: "the regroup box reads \"17 ones = 1 ten + [ ] ones\" and the tens step asks for \"the new one you made\": the trade, not \"carry the 1\" (Curriculum fixes-02, K-3 g2-regroup rewrite, 2026-10-06)",
    explain: "the regroup step says why: \"17 = 10 + 7. Keep 7 ones and move the new ten to the tens.\" (same rewrite); the hints now ask about cubes and rods",
    work: "the regroup line is \"17 ones = 1 ten + 7 ones\" (same rewrite)" },
  "g4-divide": { prompt: "the tens step asks for the biggest tens number, so only one answer fits (reviewer, 2026-10-03)", checks: "a new slip for too few tens; (Curriculum fixes-02 Part C, 2026-10-06) named slips on Subtract, Divide what's left and The answer",
    pre: "g3-divfacts: division facts come first (Curriculum fixes-02 Part C, 2026-10-06, Order 2)" },
  "g5-divide": { prompt: "the tens step asks for the biggest tens number, so only one answer fits (reviewer, 2026-10-03)",
    checks: "new named slips on Subtract and Divide what's left: \"Added instead of took away\", \"One too many\", \"One too few\" (Curriculum fixes-02 Part C, 2026-10-06)" },
  "g4-fracwhole": { steps: "the last step is named \"Write as a mixed number\", not \"Simplify\" (reviewer, 2026-10-03)", checks: "step names appear in slip messages; a wrong top repeats the new hint",
    hint: "the top hint asks \"Each group has 1 piece. How many pieces are in all the groups?\": \"5 groups of 1 piece\" gave the answer (Curriculum fixes-02 Part C, 2026-10-06)", explain: "Show me starts from the new hint",
    pre: "g4-likefrac: W × n/d is adding like fractions again and again (Curriculum fixes-02 Part C, 2026-10-06, Order 2)" },
  "g3-split": { unit: "3rd grade has units now; this lesson lives in Multiplication and division",
    steps: "a first step \"Split each row\" asks \"8 is 5 and how many more?\", so the learner makes the cut (Curriculum fixes-02, K-3 g3-split rewrite, 2026-10-06); the recorded steps follow it unchanged in answer",
    prompt: "the multiply steps ask about the picture: \"How many in the 6 rows of 5?\"; the sum step asks to put the arrays back together (same rewrite)",
    checks: "\"Add the parts\" names keeping only one part and a part added wrong, instead of the generic nudge (same rewrite)",
    explain: "each multiply step says which small array it is, and the sum says the two make the whole array, not just the sum (Review v43 item 10: step text says why, 2026-10-06)",
    pre: "builds up from g3-facts and now comes after the facts and division facts: every part of the split is a times fact (Curriculum fixes-02, K-3 Order 1, 2026-10-06)" },
};
